<?php
/**
 * @var $block \Codilar\VendorTable\Block\Display
 */
if ($block->getCollection()=== 1) {
    ?>
<h3> <?=__("No record found")?></h3>
<?php
} else {
        ?>

    <div class="my-module">
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>

                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($block->getCollection() as $item): ?>
                <tr>
                    <td><?= $item->getId() ?></td>
                    <td><?= $item->getName() ?></td>

                    <td><?= $item->getEmail() ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
    }
?>
