<?php
$product = $block->getProduct();
$attrData = $product->getData('custom_datapatch');
$attrLabel = $product->getResource()->getAttribute('custom_datapatch')->getStoreLabel();
$blockTitle = $this->getData('title');
if ($attrData !== "") :
    ?>
    <div class="product-full-width-section">
        <h2 class="product-section-title"><?= $blockTitle; ?></h2>
        <div class="product-attribute">
            <span class="attribute-label"><?= $attrLabel ?>:</span>
            <span class="attribute-value"><?= $attrData ?></span>
        </div>
    </div>
<?php endif; ?>
